id: nictiz.nl.gbb
canonical: http://nictiz.nl/gbb
name: PatientSummary
status: draft
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2026+
releaseLabel: ci-build

publisher:
  name: Nictiz
  url: https://nictiz.nl

parameters:
  excludettl: true

  path-resource:
    - generated/requirements
    - generated/logicalmodels
    - generated/vocabulary
    - generated/resources

  path-pages:
    - generated/pagecontent

  i18n-default-lang: nl
  i18n-lang: en

  translation-sources:
    - input/translations/en
    - input/translations/nl

  logging: progress
  path-liquid-template: template/liquid

menu:
  Home: index.html
  Functional design: functionaldesign.html

  Requirements:
    Overview: overview.html
    Requirements: requirements.html

  Specification:
    Specifications: specifications.html
    Logical Model: StructureDefinition-PatientSummary-model.html
    FHIR Profile: StructureDefinition-nl-patient-Summary.html
    Dependencies: dependencies.html

  Testing: testing.html
  Validation: validation.html
  Artefacts: artifacts.html

instanceOptions:
  manualSliceOrdering: true