name: Build IG for branch
on: [push]
jobs:
  GenerateArtifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Create and checkout branch for generated artifacts
        id: create-branch
        run: |
          current_branch=$(git branch --show-current)
          generated_branch="_generated_${current_branch}"
          git branch -f "$generated_branch" "$current_branch"
          git switch "$generated_branch"
          echo "generated_branch=$generated_branch" >> "$GITHUB_OUTPUT"
      - name: Generate artifacts
        run: |
          cd scripts
          npm install
          cd ..
          node scripts/excel-to-artifacts.js input/requirements generated
      - name: Commit generated artifacts
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'github@noreply.github.com'
          git add -f generated
          git commit -m "Check in generated artifacts"
          git push --force --set-upstream origin ${{ steps.create-branch.outputs.generated_branch }}
